### ISSUE TITLE
coding: integrate google calendar in events page

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#121]
## Description
As a developer, I need to integrate google calendar in events page , so that the user can see all the events related to community.

## Mocks
![image](https://user-images.githubusercontent.com/62046625/89104737-34a9f780-d439-11ea-813f-a99824639650.png)

the spacing is 16 from both sides

### Update [Required]
- [ ]  Follows all the design guidelines as mentioned and is responsive enough on large screen devices.
- [ ]  the events which we organise should be updated in the calendar as mentioned

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
3 hours

**Comment by RiaDhanani** [comment]
I just had a few questions. Are we building a web app or a mobile app because the picture looks like a part of a web app. Also, can we add a link to the google calender ? Does this issue mean we need to show a google calender component on our UI ?

**Comment by nandini45** [comment]
@RiaDhanani  a web app to ans your question. we have to integrate that calendar in that page not just add the link.
yeah we have to show a google calendar in that page.
@Sonal240  this was your design can you further help our out
and did i answer here questions correctly?

**Comment by Sonal240** [comment]
Yep @nandini45

**Comment by nandini45** [comment]
@RiaDhanani  are u willing to work on it?

**Comment by RiaDhanani** [comment]
@nandini45 Is it okay if I use iframe to get the google calender on the page?

**Comment by Sonal240** [comment]
Make sure it is responsive... We are developing it on react native so that in near future if required we may convt it to an app

**Comment by RiaDhanani** [comment]
> @nandini45 Is it okay if I use iframe to get the google calender on the page?

?

**Comment by RiaDhanani** [comment]
@nandini45 @Sonal240 To use iframes in react native, I tried adding the react-native-webview dependency but it has many configuration issues. There isn't really another way of adding iframes that I could find, so is there anything else  that I could try?

**Comment by Sonal240** [comment]
Try using an API instead of iframe

**Comment by nandini45** [comment]
@RiaDhanani  any update?

**Comment by RiaDhanani** [comment]
I couldn't really get it done with an iframe as well so I've unassigned myself.

**Comment by shravani05** [comment]
Can I work on this issue?

**Comment by gaurivn** [comment]
Sure, assigning you @shravani05

**Comment by shravani05** [comment]
I installed the react-google-calendar-api from the npm package.
But in order to access the API, I need googleApi clientId and ApiKey. So do you already have one or should I create my own credentials on https://console.developers.google.com/flows/enableapi?apiid=calendar ?
PS: I am following the above steps as per https://www.npmjs.com/package/react-google-calendar-api

**Comment by shravani05** [comment]
@gaurivn I have added the google calendar using iframe of Google Calendar, but the iframe looks different from the expected output. Following are the screenshots of the current Events page
![Events2](https://user-images.githubusercontent.com/43898702/92108861-a644df00-ee05-11ea-829d-7ca250138f8b.png)
![Events1](https://user-images.githubusercontent.com/43898702/92108868-a80ea280-ee05-11ea-8299-6f69ca6f017d.png)

I read about using api, and what I came to the conclusion is that instead of using iframe directly like above, I can use BigCalendar or similar from the react npm package and integrate that with the events of the Google Calendar. But doing the same still won't give the Google calendar on the page, it will show big calendar(with events of the google calendar of the given api). So can you please correct me if I'm wrong? 
I have attached this image of big calendar from the web, to get the idea of the output
![react-big-calendar](https://user-images.githubusercontent.com/43898702/92109996-9c23e000-ee07-11ea-82e9-04d92126b40a.jpg)

**Comment by nandini45** [comment]
it seems fine to me
@annabauza  can you review this issue?

**Comment by nandini45** [comment]
@shravani05 are you done with the work?
i think using big calendar will be fine as long as all the updates are there in it.

**Comment by shravani05** [comment]
Yes, currently I have an iframe of the Google Calendar associated with my google account. In future, you can just replace it with the iframe of the Google Calendar according to which you want to make the updates. 
So, now the work is done and the output is shown in the images I had sent earlier. So, I think there is no need to use Big Calendar, as it will give same results as I am getting now by using an iframe.
But if you want me to add Big Calendar with APIs instead of what I have done using iframe, I'll do the needful. So, please let me know what to do. @nandini45

**Comment by nandini45** [comment]
ok create a PR we can review it there further
 @shravani05  and sorry for the late comment.
 i missed your update among all

**Comment by shravani05** [comment]
@nandini45 no problem.
I have made the PR #159
