### ISSUE TITLE
Bug: Footer is held in the middle on programs tab

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/anitab-org.github.io#224]
### Describe the bug
Footer is held in the middle of the screen which looks bad.

### To Reproduce
1. Go to 'https://anitab-org.github.io/'
2. Click on 'Programs'
3. See the footer

### Expected behavior

Footer on programs tab should be at the bottom & style the program timeline so that the programs page doesn't look empty & bad.
### Screenshots
![Screenshot_2021-02-06 AnitaB org Open Source](https://user-images.githubusercontent.com/44670961/107080612-8c298580-6817-11eb-8169-dafd87915e03.png)

### Desktop (please complete the following information):
 - OS: Ubuntu 20.04
 - Browser Firefox

**Comment by prathameshbhalekar** [comment]
Can I work on it?

**Comment by annabauza** [comment]
There is another issue of footer i think, can we double check it?

**Comment by Vishal-raj-1** [comment]
@annabauza Yes there is one issue related to footer. But #165 is about the design of the footer means they want to create a whole new page for contact section. But this issue is related to the placement of the footer as mentioned by @chinmaym07 . I think we can place footer in bottom, it has nothing to do with footer design. 


@chinmaym07 If you want to place footer at the bottom of the page then I would suggest place the above section at the centre and increase the height of the section. What do you say @annabauza ??

**Comment by chinmaym07** [comment]
Yes . I was also thinking to do that . that's why I have added above 'to style the program timeline'  .It will look better as compared to one that we have write now. Thanks @Vishal-raj-1 . If it's a valid issue .please assign it to @prathameshbhalekar as he want to work on this issue. 👍🏻

**Comment by prathameshbhalekar** [comment]
> Yes . I was also thinking to do that . that's why I have added above 'to style the program timeline' .It will look better as compared to one that we have write now. Thanks @Vishal-raj-1 . If it's a valid issue .please assign it to @prathameshbhalekar as he want to work on this issue. 👍🏻

Thanks @chinmaym07

**Comment by prathameshbhalekar** [comment]
Should I start working on it? It's not assigned to me yet.
