### ISSUE TITLE
Add relative paths to files located within the repository

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#29]
## Description
As a contributor,
I need see relative paths to repository files on the README,
so that I can see them properly on my fork README rendering.

On README the links to LICENSE, CONTRIBUTING.md, etc located within the repo, have absolute links to this organization repo, this causes to within our forks, it is linked to these files in the `anitab-org` organization files instead of on my fork's files.

### Update [Required]
- [ ] Turn paths to local files from absolute paths to relative paths on README

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by nandini45** [comment]
can i work on it?
@isabelcosta

**Comment by isabelcosta** [comment]
This is also labeled as first timers @nandini45. You are still working on that other issue right?

**Comment by nandini45** [comment]
no  i have done that and merged
@isabelcosta

**Comment by annabauza** [comment]
@nandini45 please feel free to work on that :)

**Comment by nandini45** [comment]
@isabelcosta  i had a question can you tell me what I am thinking is correct or not?
 you want me to change the path that is when in my fork repo i click on contributing guideline i should stay in my forked repo instead of going to the original repo..right?
and i had a suggestion that we can create a separate readme for forking and cloning the repo and mention them in the readme on clicking that the fork details opens up??

**Comment by isabelcosta** [comment]
> you want me to change the path that is when in my fork repo i click on contributing guideline i should stay in my forked repo instead of going to the original repo..right?

Yes, correct :)

> i had a suggestion that we can create a separate readme for forking and cloning the repo and mention them in the readme on clicking that the fork details opens up??

That seems like a different issue, not part of this issue. Can you please create an issue for that to first get approved? @nandini45

**Comment by nandini45** [comment]
i can't seem to get the forked repo address. the approach that i was using was that in the given link below i will change anitab-org to the forked user repository name , it is even working but i am not able to change it so that when a new user forks he remain in his repository
@isabelcosta 
change this link
https://github.com/github-username/anitab-org.github.io/blob/develop/CONTRIBUTING.md
to this link
https://github.com/nandini45/anitab-org.github.io/blob/develop/CONTRIBUTING.md

**Comment by isabelcosta** [comment]
@nandini45 can you please submit the PR. I can show you how its done by reviewing it. I thin you are almost there.

The relative path would be:
```
[CONTRIBUTING.md](CONTRIBUTING.md)
```

**Comment by nandini45** [comment]
i think i missed this update among all the emails about this repo.. sorry Isabel.. i will submit this asap

**Comment by isabelcosta** [comment]
If you wish to leave this for other first-timer contributors and focus on other issues, you can do that :) This is a low priority and low hanging fruit :) otherwise, feel free to send the PR

**Comment by nandini45** [comment]
@isabelcosta  I think you are right. because i am lagging behind now. and i think with with new users we may have a different approach or any new way. who knows what.
should i unassign myself? 
 and Isabel i saw that in the mentorship backend too we have the same issue that is we don't stay in our forked repository. any reasons why?

**Comment by isabelcosta** [comment]
@nandini45 its there because no one reported yet 🙈 do you wish to create a issue for it ;)
I can create as well, but feel free to do it if you want :)

**Comment by garimasingh128** [comment]
@isabelcosta Hi Isabel. I am a first time contributor. I tried to solve this issue in my Pull Request: https://github.com/anitab-org/anitab-org.github.io/pull/43. Kindly review it.

**Comment by nandini45** [comment]
@isabelcosta  do i have to do anything because someone already assigned this to someone i suppose.
so i think you might have got a new contributor already.
